{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "dde47555_a3ee7b7a",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1000003
      },
      "writtenOn": "2025-01-16T15:12:07Z",
      "side": 1,
      "message": "@mnaser@vexxhost.com \n\nWith this patch, I got this error when start neutron-ironic-agent on my AIO env.\n\n2025-01-16 15:04:25.307 1 ERROR networking_baremetal.ironic_client [None req-d9649507-514a-45d6-b6a3-2d420e33f8b1 - - - - - -] Failed to establish a connection with ironic, reason: The request you have made requires authentication. (HTTP 401) (Request-ID: req-ec0c99aa-c7b7-4161-919e-5dd2529546bb): keystoneauth1.exceptions.http.Unauthorized: The request you have made requires authentication. (HTTP 401) (Request-ID: req-ec0c99aa-c7b7-4161-919e-5dd2529546bb)2025-01-16 15:04:25.308 1 CRITICAL neutron [None req-d9649507-514a-45d6-b6a3-2d420e33f8b1 - - - - - -] Unhandled error: keystoneauth1.exceptions.http.Unauthorized: The request you have made requires authentication. (HTTP 401) (Request-ID: req-ec0c99aa-c7b7-4161-919e-5dd2529546bb)",
      "revId": "071a4a6871d0f96b28fe5dd9b4c36219491ec9ef",
      "serverId": "a369f105-6bff-480f-8aaf-eafd1f85bb44"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "53398c58_751cd287",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1000000
      },
      "writtenOn": "2025-01-16T19:49:43Z",
      "side": 1,
      "message": "@dong.ma@vexxhost.com I wonder if this is because it uses the `ironic` user to authenticate against Keystone, but you don\u0027t have Ironic deployed so it fails.\n\nI was never a fan of why we use passwords for _other_ services to talk to Keystone, so maybe you can make it so that it uses the Neutron credentials (service user) in the `ironic` section?",
      "revId": "071a4a6871d0f96b28fe5dd9b4c36219491ec9ef",
      "serverId": "a369f105-6bff-480f-8aaf-eafd1f85bb44"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "b6eafc5a_8d19420f",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1000003
      },
      "writtenOn": "2025-01-17T01:02:43Z",
      "side": 1,
      "message": "yes, it\u0027s related I didn\u0027t have Ironic deployed, after updated to use Neutron credentials, i got this error:\n\n2025-01-17 00:52:29.679 1 ERROR networking_baremetal.ironic_client [None req-a49d0b60-9b7e-4953-b4db-72264f7353c0 - - - - - -] Failed to establish a connection with ironic, reason: public endpoint for baremetal service not found: keystoneauth1.exceptions.catalog.EndpointNotFound: public endpoint for baremetal service not found",
      "parentUuid": "53398c58_751cd287",
      "revId": "071a4a6871d0f96b28fe5dd9b4c36219491ec9ef",
      "serverId": "a369f105-6bff-480f-8aaf-eafd1f85bb44"
    }
  ]
}